spring:
  application:
    name: findex
  datasource:
    url: ${DB_URL}              # DB 경로 (DB명 잘 확인하기)
    username: ${DB_USERNAME}    # 개별 DB 접근 유저 (환경변수사용)
    password: ${DB_PASSWORD}    # 개별 DB 접근 유저 (환경변수사용)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update          # 없으면 생성 있다면 변경 된 사항 확인하여 수정
    show-sql: true              # JPQL로 진행 된 실제 쿼리문 확인용
    properties:
      hibernate:
        format_sql: true        # SQL 콘솔 포맷핑 (로그, 콘솔의 SQL을 좀 더 이쁘게 출력)
        highlight_sql: true     # SQL 출력을 ANSI escape codes를 사용하여 색을 부여
        use_sql_comments: true  # 보다 쉬운 디버깅을 위해 SQL 내부에 /* */의 주석을 추가


logging:
  level:
    org:
      hibernate:
        SQL: debug               # Hibernate가 DB로 날리는 SQL문을 찍어주는 로거
        type:
          descriptor:
            sql: trace           # 쿼리문 바인딩 되는 실제 값 확인
